# Site settings
title: Sandid blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "https://sandidsisir.github.io"


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
